package co.rumpy.client.android.adapter;

import java.util.ArrayList;
import java.util.List;

import co.rumpy.client.android.R;
import co.rumpy.client.android.adapter.ContactListArrayAdapter.ViewHolder;
import co.rumpy.client.android.structure.ContactDetail;
import co.rumpy.client.android.structure.RecentChatDetail;

import android.app.Activity;
import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.TextView;

public class ChatListArrayAdapter extends ArrayAdapter<RecentChatDetail> {
	
	private final Activity context;
	private ArrayList<RecentChatDetail> chats;
	
	public ChatListArrayAdapter(Activity context, ArrayList<RecentChatDetail> chats) {
		super(context, R.layout.layout_row_recentchat, chats);
		this.context = context;
		this.chats = chats;
	}
	
	static class ViewHolder {
		
		public ImageView thumbImage;
		public TextView fullname;
		public TextView lastChat;
		
	}
	
	@Override
	public View getView(int position, View convertView, ViewGroup parent) {
		
		View rowView = convertView;
		
		if (rowView == null) {
			
			LayoutInflater layoutInflater = context.getLayoutInflater();
			rowView = layoutInflater.inflate(R.layout.layout_row_recentchat, null);
			ViewHolder viewHolder = new ViewHolder();
			
			viewHolder.thumbImage = (ImageView) rowView.findViewById(R.id.recent_imageview_contactimage);
			viewHolder.fullname = (TextView) rowView.findViewById(R.id.recent_textview_fullname);
			viewHolder.lastChat = (TextView) rowView.findViewById(R.id.recent_textview_lastchat);
			
			rowView.setTag(viewHolder);
		}
		
		ViewHolder holder = (ViewHolder) rowView.getTag();
		RecentChatDetail rcd = chats.get(position);
		
		// initiate contact thumb image
		// should be generated by thumb file name,
		// then retreive that image from internal storage
		
		String thumbImage = rcd.getImageThumbName();
		if (thumbImage.equals("bagas.jpg")) {
			holder.thumbImage.setImageResource(R.drawable.bagas); // this is wrong, should get from internal storage
		} else if (thumbImage.equals("diska.jpg")){
			holder.thumbImage.setImageResource(R.drawable.diska);
		} else {
			holder.thumbImage.setImageResource(R.drawable.thumb);
		}
		
		// initiate contact fullname
		String fullname = rcd.getFullname();
		holder.fullname.setText(fullname);
		
		// initiate contact's last presence (status update)
		String lastChat = rcd.getLastChat();
		holder.lastChat.setText(lastChat);
		
		return rowView;
	}

}
