package co.rumpy.client.android.adapter;

import java.util.ArrayList;

import co.rumpy.client.android.R;
import co.rumpy.client.android.structure.ContactDetail;

import android.app.Activity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.TextView;

public class ContactListArrayAdapter extends ArrayAdapter<ContactDetail> {
	
	private final Activity context;
	private ArrayList<ContactDetail> contacts;
	
	static class ViewHolder {
		
		public ImageView thumbImage;
		public TextView fullname;
		public TextView lastPresence;
	}
	
	public ContactListArrayAdapter (Activity context, ArrayList<ContactDetail> contacts) {
		
		super(context, R.layout.layout_row_contactlist, contacts);
		this.context = context;
		this.contacts = contacts;
	}
	
	@Override
	public View getView(int position, View convertView, ViewGroup parent) {
		
		View rowView = convertView;
		
		if (rowView == null) {
			LayoutInflater layoutInflater = context.getLayoutInflater();
			rowView = layoutInflater.inflate(R.layout.layout_row_contactlist, null);
			ViewHolder viewHolder = new ViewHolder();
			
			viewHolder.thumbImage = (ImageView) rowView.findViewById(R.id.contactThumb);
			viewHolder.fullname = (TextView) rowView.findViewById(R.id.contactFullname);
			viewHolder.lastPresence = (TextView) rowView.findViewById(R.id.contactLastPresence);
			
			rowView.setTag(viewHolder);
		}
		
		ViewHolder holder = (ViewHolder) rowView.getTag();
		ContactDetail contact = contacts.get(position);
		
		// initiate contact thumb image
		// should be generated by thumb file name,
		// then retreive that image from internal storage
		
		String thumbImage = contact.getImageThumbName();
		if (thumbImage.equals("bagas.jpg")) {
			holder.thumbImage.setImageResource(R.drawable.bagas); // this is wrong, should get from internal storage
		} else if (thumbImage.equals("diska.jpg")){
			holder.thumbImage.setImageResource(R.drawable.diska);
		} else {
			holder.thumbImage.setImageResource(R.drawable.thumb);
		}
		
		// initiate contact fullname
		String fullname = contact.getFullname();
		holder.fullname.setText(fullname);
		
		// initiate contact's last presence (status update)
		String presence = contact.getLastPresence();
		holder.lastPresence.setText(presence);
		
		return rowView;
		
	}

}
